<a href="https://colab.research.google.com/github/ANUPAM7209/ANUPAM7209/blob/main/pytorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [57]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [58]:
df.shape

(569, 33)

In [59]:
df.drop(columns=['id' , 'Unnamed: 32'], inplace = True)

In [60]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

#Train-Test-Split

In [61]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:], df.iloc[:, 0], test_size=0.2)

#Scaling

In [62]:
#in neural network we pass generally same scale data
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [63]:
x_train

array([[-1.12253906, -0.43655533, -1.11969202, ..., -1.21885865,
        -0.04596586, -0.34268879],
       [-0.01349387,  0.44304199, -0.07746929, ..., -0.54333849,
        -1.12159577, -0.44687649],
       [-0.37834946,  2.35155819, -0.43302143, ..., -0.76866569,
        -0.81834186, -1.06169243],
       ...,
       [-0.54050751, -0.31056526, -0.5610876 , ..., -0.41014167,
         0.54043674, -0.52664519],
       [-0.79822297,  1.80326809, -0.83701965, ..., -1.44772341,
        -0.07779915, -0.73447794],
       [ 1.09265565, -1.42814382,  0.96770233, ..., -0.48519946,
        -1.86381392, -1.39433335]])

In [64]:
y_train

217    B
235    B
552    B
550    B
137    B
      ..
399    B
423    B
367    B
231    B
491    B
Name: diagnosis, Length: 455, dtype: object

#Lable Encoder

In [65]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [66]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,

#Numpy arrays to Pytorch tensors

In [67]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [68]:
x_train_tensor.shape

torch.Size([455, 30])

In [51]:
y_train_tensor.shape

torch.Size([455])

#Definig the model

In [96]:
class MySimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1] , 1 , dtype = torch.float64 , requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64 , requires_grad=True)

  def forward(self, X):
      z = torch.matmul(X, self.weights) + self.bias
      y_pred = torch.sigmoid(z)
      return y_pred

  def loss_function(self, y_pred, y):
    #clamp prediction to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1- epsilon)

    #calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor)* torch.log(1- y_pred)).mean()
    return loss


#Important Parameter

In [105]:
learning_rate = 0.1
epochs = 25

#Traning pipeline

In [106]:
#create model
model = MySimpleNN(x_train_tensor)

#Train a model
#define loop
for epoch in range(epochs):
    #1.forward pass
    y_pred = model.forward(x_train_tensor)
    #print(y_pred)

    #2.loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)
    #print(f"Epoch: {epoch + 1}, loss: {loss.item()}")

    #now for derivative use Autograd
    #3. backward pass
    loss.backward()

    #4. parameters update
    with torch.no_grad():
      model.weights -= learning_rate * model.weights.grad
      model.bias -= learning_rate * model.bias.grad

    #5.zero grad
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    #6. print loss in each epoch
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")


Epoch: 1, Loss: 3.605705217326031
Epoch: 2, Loss: 3.4666740169639194
Epoch: 3, Loss: 3.32500775082873
Epoch: 4, Loss: 3.179666346386789
Epoch: 5, Loss: 3.033778243241604
Epoch: 6, Loss: 2.886853076270702
Epoch: 7, Loss: 2.7392624080587127
Epoch: 8, Loss: 2.585290032784041
Epoch: 9, Loss: 2.4210567308144664
Epoch: 10, Loss: 2.260015007172205
Epoch: 11, Loss: 2.104328762122008
Epoch: 12, Loss: 1.949911181597233
Epoch: 13, Loss: 1.801001720125134
Epoch: 14, Loss: 1.6611135807628412
Epoch: 15, Loss: 1.5298880784251718
Epoch: 16, Loss: 1.4075758666831866
Epoch: 17, Loss: 1.299353295598517
Epoch: 18, Loss: 1.205899673510994
Epoch: 19, Loss: 1.1272316372650903
Epoch: 20, Loss: 1.0626853763718873
Epoch: 21, Loss: 1.0109872252394263
Epoch: 22, Loss: 0.9703387982523907
Epoch: 23, Loss: 0.9385792443905
Epoch: 24, Loss: 0.9135378930873904
Epoch: 25, Loss: 0.8933765051412549


In [100]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

#Model Evaluation

In [111]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float()
  #accuracy code
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")


Accuracy: 0.5438596606254578
