<a href="https://colab.research.google.com/github/ANUPAM7209/ANUPAM7209/blob/main/pytorch_autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
def dy_dx(x):
  return 2*x

In [7]:
dy_dx(3)

6

In [8]:
import math

def dz_dx(x):
  return 2*x*math.cos(x**2)

In [9]:
dz_dx(2)

-2.6145744834544478

In [19]:
import torch

In [20]:
x = torch.tensor(3.0, requires_grad=True) # it understand that it want to calculate the derivatve

In [21]:
y = x**2

In [22]:
x

tensor(3., requires_grad=True)

In [23]:
y

tensor(9., grad_fn=<PowBackward0>)

In [24]:
y.backward()

In [25]:
x.grad # to see the value of the gradient

tensor(6.)

In [26]:
import math

def dz_dx(x):
  return 2*x*math.cos(x**2)


In [27]:
dz_dx(3)

-5.466781571308061

In [28]:
x = torch.tensor(3.0, requires_grad=True)

In [29]:
y = x**2

In [30]:
z = torch.sin(y)

In [31]:
x

tensor(3., requires_grad=True)

In [32]:
y

tensor(9., grad_fn=<PowBackward0>)

In [33]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

for dz/dx we need to move towards backward direction


In [34]:
z.backward()

In [35]:
x.grad

tensor(-5.4668)

Next example

In [36]:
import torch

#inputs
x = torch.tensor(6.7) #Input feature
y = torch.tensor(0.0) #True label(binary)

w = torch.tensor(1.0) # weight
b = torch.tensor(0.0) # Bias

In [37]:
# Binary Cross-Entropy Loss for scalar
def binary_cross_entropy_loss(prediction, target):
  epsilon = 1e-8 #To prevent log
  prediction = torch.clamp(prediction, epsilon , 1-epsilon)
  return -(target* torch.log(prediction) + (1 - target)* torch.log(1 - prediction))

In [39]:
# Forward pass
z = w*x + b # weighted sum(linear part)
y_pred = torch.sigmoid(z) # predicted probablity

#compute binary cross-entropy loss
loss =  binary_cross_entropy_loss(y_pred, y)

In [40]:
#Derivative:
#1. dL/d(y_pred): Loss with respect to the prediction (y_pred)
dloss_dy_pred = (y_pred - y)/(y_pred*(1-y_pred))

#2. dy_pred/dz: Prediction (y_pred) with respect to z (sigmoid derivative)
dy_pred_dz = y_pred*(1-y_pred)

#3. dz/dw and dz/db: z with respect to w and b
dz_dw = x #dz/dw =x
dz_db = 1 #dz/db = 1 (bias contributes directly to z)

dL_dw = dloss_dy_pred * dy_pred_dz * dz_dw
dL_db = dloss_dy_pred * dy_pred_dz * dz_db

In [41]:
print(f"Manual Gradient of loss w.r.t weight (dw):{dL_dw}")
print(f"Manual Gradient of loss w.r.t bais:{dL_db}")

Manual Gradient of loss w.r.t weight (dw):6.691762447357178
Manual Gradient of loss w.r.t bais:0.998770534992218


#Now we use autograd

In [42]:
 x = torch.tensor(6.7)
 y = torch.tensor(0.0)

In [43]:
w = torch.tensor(1.0 , requires_grad=True)
b = torch.tensor(0.0 , requires_grad=True)

In [44]:
w

tensor(1., requires_grad=True)

In [45]:
b

tensor(0., requires_grad=True)

In [46]:
z = w*x +b

In [47]:
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [48]:
y_pred = torch.sigmoid(z)

In [49]:
y

tensor(0.)

In [50]:
loss = binary_cross_entropy_loss(y_pred , y)
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [51]:
loss.backward()

In [52]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


Vector input tensors

In [60]:
x = torch.tensor([1.0 ,2.0,3.0], requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [61]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [63]:
y.backward()

In [64]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [65]:
#clearing grad -> because multiple time runing the forward and backward  grad will be acumulate

In [66]:
#for clearing the gradiant use inplace method
x.grad.zero_()

tensor([0., 0., 0.])

How to disable tracking

In [71]:
# disable gradient tracking -> if don't want to open backward pass so we have to disable it
x = torch.tensor(2.0, requires_grad=True)
x

tensor(2., requires_grad=True)

In [72]:
y = x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [73]:
y.backward()
x.grad

tensor(4.)

In [69]:
#option 1 - requires_grad_(False)
#option 2 - detach()
#option 3 - torch.no_grad()

In [74]:
x.requires_grad_(False)

tensor(2.)

In [75]:
x

tensor(2.)

In [76]:
y = x**2

In [77]:
y

tensor(4.)

In [78]:
#2
x = torch.tensor(2.0 , requires_grad=True)
x

tensor(2., requires_grad=True)

In [79]:
z = x.detach()
z

tensor(2.)

In [80]:
y = x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [81]:
y1 = z**2
y1

tensor(4.)

In [82]:
#after this u can do backward tracking for y but not for y1

In [83]:
#3
x = torch.tensor(2.0 , requires_grad=True)
x

tensor(2., requires_grad=True)

In [86]:
with torch.no_grad(): # in this y.backward won't work
  y = x**2

In [87]:
y

tensor(4.)