<a href="https://colab.research.google.com/github/ANUPAM7209/ANUPAM7209/blob/main/tensors-in-pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensors in pytorch

In [1]:
import torch
print(torch.__version__)

2.8.0+cu126


In [2]:
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not available. Using CPU.")

GPU is available!
using GPU: Tesla T4


Ceating a Tensor

In [4]:
#using empty
a = torch.empty(2,3)

In [5]:
#check type
type(a)

torch.Tensor

In [6]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#using rand
torch.rand(2,3)

tensor([[0.9915, 0.6018, 0.0857],
        [0.4064, 0.0439, 0.5954]])

In [9]:
#use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
#other ways
#arange
print("using arange ->", torch.arange(0,10))

#using linspace
print("using linspace ->", torch.linspace(0,10,10))

#using eye
print("using eye ->", torch.eye(5))

#using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensor Shape


In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3833745696854456163]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [26]:
#torch.rand_like(x)
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tensor Data Type

In [21]:
#find data type
x.dtype

torch.int64

In [22]:
#assign data type
torch.tensor([1.0,2.0,3.0,4.0], dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

In [23]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
#usig to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Mathematical operation

1. Scalar operation

In [28]:
x = torch.rand(2,2)
x

tensor([[0.9969, 0.7565],
        [0.2239, 0.3023]])

In [29]:
#addition
x+2
#substraction
x-2
#multiplication
x*3
# division
x/3
# int division
(x*100)//3
# mod
((x*100)//3)%2
# power
x**2

tensor([[0.9938, 0.5723],
        [0.0501, 0.0914]])

2. Element Wise operation

In [30]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])
tensor([[0.7445, 0.4892, 0.2426],
        [0.7003, 0.5277, 0.2472]])


In [31]:
#add
a+b
#sub
a -b
#multiply
a*b
#division
a / b
#power
a**b
#mod
a % b

tensor([[0.1784, 0.3346, 0.0706],
        [0.2767, 0.4440, 0.2063]])

In [32]:
c = torch.tensor([1,-2 , 3, -4])

In [33]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [34]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [35]:
d =torch.tensor([1.9, 2.3, 3.7, 4.4])

In [36]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [37]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [38]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [39]:
#clamp
torch.clamp(d , min=2 , max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction operation

In [45]:
e = torch.randint(size=(2,3), low=0 , high=10 , dtype=torch.float32)
e

tensor([[9., 7., 5.],
        [9., 8., 9.]])

In [46]:
#sum
torch.sum(e)
#sum along columns
torch.sum(e , dim=0)
#sum along row
torch.sum(e, dim=1)

tensor([21., 26.])

In [48]:
#mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([9.0000, 7.5000, 7.0000])

In [50]:
#median
torch.median(e)

tensor(8.)

In [51]:
#max and min
torch.max(e)
torch.min(e)

tensor(5.)

In [52]:
#product
torch.prod(e)

tensor(204120.)

In [53]:
# standard deviation
torch.std(e)

tensor(1.6021)

In [54]:
#variance
torch.var(e)

tensor(2.5667)

In [55]:
#argmax
torch.argmax(e)

tensor(0)

In [56]:
#argmin
torch.argmin(e)

tensor(2)

Matrix Operation

In [57]:
f = torch.randint(size=(2,3) , low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)
print(f)
print(g)

tensor([[7, 9, 2],
        [6, 7, 7]])
tensor([[8, 3],
        [6, 1],
        [5, 5]])


In [58]:
#matrix multiplication
torch.matmul(f , g)

tensor([[120,  40],
        [125,  60]])

In [59]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1 , vector2)

tensor(11)

In [61]:
#transpose
torch.transpose(f,0,1)

tensor([[7, 6],
        [9, 7],
        [2, 7]])

In [62]:
h = torch.randint(size=(3,3) , low=0 , high=10 , dtype=torch.float32)
h

tensor([[0., 4., 3.],
        [8., 8., 3.],
        [3., 5., 0.]])

In [63]:
#deteminant
torch.det(h)

tensor(84.)

In [64]:
#inverse
torch.inverse(h)

tensor([[-0.1786,  0.1786, -0.1429],
        [ 0.1071, -0.1071,  0.2857],
        [ 0.1905,  0.1429, -0.3810]])

Comparision Operation

In [66]:
i = torch.randint(size=(2,3), low=0 , high=10)
j = torch.randint(size=(2,3), low=0 ,high=10)
print(i)
print(j)

tensor([[9, 5, 0],
        [4, 2, 7]])
tensor([[1, 1, 5],
        [4, 4, 1]])


In [67]:
#greater than
i > j
#less than
i ,j
#not equal to
i != j
#equal to
i == j
#greater than equal to
# less than equal to

tensor([[False, False, False],
        [ True, False, False]])

6. Special function

In [78]:
k = torch.randint(size=(2,3) , low=0 , high=10 , dtype=torch.float32)
k

tensor([[6., 1., 4.],
        [5., 6., 9.]])

In [79]:
#log
torch.log(k)

tensor([[1.7918, 0.0000, 1.3863],
        [1.6094, 1.7918, 2.1972]])

In [80]:
#exp
torch.exp(k)

tensor([[4.0343e+02, 2.7183e+00, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 8.1031e+03]])

In [81]:
#sqrt
torch.sqrt(k)

tensor([[2.4495, 1.0000, 2.0000],
        [2.2361, 2.4495, 3.0000]])

In [82]:
#sigmoid
torch.sigmoid(k)

tensor([[0.9975, 0.7311, 0.9820],
        [0.9933, 0.9975, 0.9999]])

In [83]:
#softmax
torch.softmax(k , dim=0)

tensor([[0.7311, 0.0067, 0.0067],
        [0.2689, 0.9933, 0.9933]])

In [84]:
#relu
torch.relu(k)

tensor([[6., 1., 4.],
        [5., 6., 9.]])

#Inplace Operations

In [85]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.6269, 0.8277, 0.6594],
        [0.0887, 0.4890, 0.5887]])
tensor([[0.7340, 0.8497, 0.9112],
        [0.4847, 0.9436, 0.3904]])


In [86]:
m.add_(n)

tensor([[1.3610, 1.6774, 1.5705],
        [0.5734, 1.4325, 0.9792]])

In [87]:
m.relu_() # to convert inplace operation

tensor([[1.3610, 1.6774, 1.5705],
        [0.5734, 1.4325, 0.9792]])

In [88]:
b = a.clone()

In [89]:
a

tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])

In [90]:
a[0][0]=10

In [91]:
a

tensor([[10.0000,  0.8238,  0.5557],
        [ 0.9770,  0.4440,  0.9478]])

In [92]:
b

tensor([[0.1784, 0.8238, 0.5557],
        [0.9770, 0.4440, 0.9478]])

In [93]:
id(a)

139883531434048

In [94]:
id(b)

139883515109824

#Tensor Operation on GPU

In [95]:
torch.cuda.is_available()

True

In [96]:
device = torch.device("cuda")

In [98]:
# creating a new tensor on GPU
torch.rand((2,3), device =device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [99]:
#moving an existing tensor to GPU
a = torch.rand(2,3)

In [100]:
b=a.to(device)

In [101]:
b+5

tensor([[5.2499, 5.3206, 5.9753],
        [5.7582, 5.6688, 5.2651]], device='cuda:0')

In [103]:
import torch
import time

#Define the size of the matrices
size = 10000 # Large size for performance comparison

#Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size , size)

#Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2) #matrix multiplication on cpu
cpu_time = time.time() - start_time

print(f"Time on CPU: {cpu_time: .4f} seconds")

#Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

#Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1 , matrix_gpu2) #Matrix multiplication on GPU
torch.cuda.synchronize() #Ensure all GPU operation are complete
gpu_time = time.time() - start_time

print(f"Time on GPU: {gpu_time: .4f} seconds")

#compare results

print("\nSpeedup (CPU time / GPU time):" , cpu_time / gpu_time)

Time on CPU:  14.9647 seconds
Time on GPU:  0.7181 seconds

Speedup (CPU time / GPU time): 20.839139599733993


#Reshaping Tensors

In [104]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [109]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [110]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [108]:
b = torch.rand(2,3,4)
b

tensor([[[0.7827, 0.4926, 0.7323, 0.4682],
         [0.4369, 0.3151, 0.6987, 0.7903],
         [0.5187, 0.7766, 0.9718, 0.5460]],

        [[0.9329, 0.9847, 0.6817, 0.2420],
         [0.6212, 0.0121, 0.0662, 0.3254],
         [0.6391, 0.1906, 0.6926, 0.0684]]])

In [112]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [113]:
#unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [114]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

#Numpy and PyTorch

In [115]:
import numpy as np

In [117]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [118]:
b = a.numpy()

In [119]:
b

array([1, 2, 3])

In [120]:
type(b)

numpy.ndarray

In [121]:
c = np.array([1,2,3])

In [122]:
c

array([1, 2, 3])

In [123]:
torch.from_numpy(c)

tensor([1, 2, 3])